## Load Data & Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/automated_healthcare_analysis_2026-02-25-1522.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110523 entries, 0 to 110522
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   APPOINTMENT_ID  110523 non-null  int64
 1   WAITING_DAYS    110523 non-null  int64
 2   DAY_OF_WEEKS    110523 non-null  int64
 3   SMS_RECEIVED    110523 non-null  int64
 4   AGE             110523 non-null  int64
 5   GENDER          110523 non-null  object
 6   TOTAL_VISITS    110523 non-null  int64
 7   NO_SHOW         110523 non-null  int64
dtypes: int64(7), object(1)
memory usage: 6.7+ MB

In [4]:
df.isnull().sum()

APPOINTMENT_ID    0
WAITING_DAYS      0
DAY_OF_WEEKS      0
SMS_RECEIVED      0
AGE               0
GENDER            0
TOTAL_VISITS      0
NO_SHOW           0
dtype: int64

In [5]:
df = df.drop(columns=['APPOINTMENT_ID'])

In [6]:
#Encode Categorical Columns
df = pd.get_dummies(df,drop_first=True)

In [12]:
df.head()

,WAITING_DAYS,DAY_OF_WEEKS,SMS_RECEIVED,AGE,TOTAL_VISITS,NO_SHOW,GENDER_M
0,0,5,0,62,3,0,0
1,0,5,0,56,3,0,1
2,0,5,0,62,3,0,0
3,0,5,0,56,3,0,1
4,0,5,0,62,2,0,0

In [11]:
df = df.astype(int)

In [9]:
df['NO_SHOW'].value_counts(normalize=True)

NO_SHOW
0    0.798105
1    0.201895
Name: proportion, dtype: float64

## ML Analysis

In [8]:
#ml libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

In [13]:
# feature and target column
X = df.drop('NO_SHOW', axis=1)
y = df['NO_SHOW']

In [14]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [15]:
# Train Logistic Regression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [16]:
#prediction
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

In [17]:
# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))

Accuracy: 0.7943451707758425
ROC-AUC: 0.6575545460981209
              precision    recall  f1-score   support

           0       0.80      0.99      0.88     17642
           1       0.31      0.02      0.03      4463

    accuracy                           0.79     22105
   macro avg       0.56      0.50      0.46     22105
weighted avg       0.70      0.79      0.71     22105